print('"""First Python Program')
print('\tDate:9/5/2015"""')
print('print("Introduction to computing using Python" " 15CS101") ')
print('print("3rd","Semester","Summer(Credited)","Course",sep="_"\ ')
print(',end = "\\nJune-July 2015")')
